<?php

declare(strict_types=1);

return [
    [
        'id' => '',
        'key' => 'brief-company-details-click-industry',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => 'f0aba162-bf46-49ed-bc29-d7428bcde98b',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-socialproject',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => 'e4cd0563-e885-4746-9c51-018a0ba64ab0',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-assets',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '8c1ece7a-0788-471a-b37d-8ecc6358d02a',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-marketing',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '2f6f9829-ce64-4c39-83e0-939f4f65c652',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-achievements',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => 'bf91fcfb-21ad-42cd-b2d3-3e838c4f5957',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-design',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => 'aab2ab32-bc30-4262-8d39-2b2da17c682d',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-product',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => 'b409145d-d9e1-4dc2-92ee-15ece4ca65d6',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-productrange',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '3d34202b-b6e4-499f-aa73-62d53caee7a8',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-ingredients',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '97a11299-5cee-4a9a-b3ec-e02cd4fd2d6e',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-country',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '271f2abc-0456-4d3b-88f9-7693413bd23b',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-innovations',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '8aaa6b53-34ef-4248-a5ea-ce0ea1a182d8',
    ],
    [
        'id' => '',
        'key' => 'brief-company-details-click-people',
        'entity_collection' => 'brand_wizard_advantages',
        'entity_id' => '190732ce-cbe7-4141-bd79-3c8b306402d2',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-bahroma',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '383c802a-f8d7-4635-8a1a-34df6e50253a',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-lemonade',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'aef89db7-5be0-4193-aec4-f89197a3c184',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-sushi',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '596b1e3c-4509-4076-9435-9dafa4615268',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-orangemix',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '462a00a3-4785-47d9-8feb-94c27c8a0698',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-spicemode',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '26a60cfa-f1a1-47bf-b26d-a10228aa8c6c',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-veggieburger',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '2e0ec151-35e2-494e-9340-2cf9ce5c623b',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-peas',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '56141565-a94e-4e25-90b0-b45c55e3cdd6',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-siggis',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '3cce7bea-1d62-43df-9ea7-155a5c1cffbd',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-apetina',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '928a5819-91cc-4d5c-9262-0bbeb7a4d3cf',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-gotham',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '9884d2ee-fc07-4973-acd3-77352fca383e',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-tetapizza',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '11658126-13ea-41f2-a088-ba4c58e95971',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-sausages',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '6710c769-5216-4f5a-b43a-f5511fc326b3',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-dovesfarm',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'ead5cbbb-4a6b-4ece-bcf0-ce1758d753ed',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-americanpicnic',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '7cdb36bc-be2b-4290-8185-f43737cfe06b',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-cereals',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '5374c62f-f440-49f7-9548-3a88e539a9b7',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-smalls',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '9b77953b-5e99-48dc-8f21-0e6524fb4f06',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-joecoffee',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '7dbb851f-a293-4247-9498-978f9e788465',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-package-click-tanzania',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'fa568615-ca80-45fd-a069-9679ec09f170',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-turbo',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '6f9e4092-e30a-4b0f-ad7e-2a425d405b9d',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-heringfoundation',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'b9311030-9a47-420d-8272-46fa4c8c5094',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-vivahjewels',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '6bd729df-ff03-4140-a649-d8a295030d80',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-oloo',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'e5bfa70f-c696-4bda-8011-ff3d9ffafd5b',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-mauracora',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '640a235c-421c-47c5-a3c1-100822606d91',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-skatra',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'ddc93143-4be2-4454-8fd1-4b76eb07b61c',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-harone',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '00bc02fc-dbb5-4d02-84be-cb699219d4cc',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-moon',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'fbbe18b6-5c96-430d-ab2a-c74ea86c1a2c',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-angelsandco',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '9d364d5a-986e-4e2b-b8b5-17604ceda559',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-olivequeen',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'ebc0a5de-94eb-4fd0-ab0c-5c885db9be4c',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-doglove',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'a381f924-21f0-4b66-ab0f-e321c297d25e',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-devine',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '74618dd9-79d1-48b8-a9cf-05d7516a33a7',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-lesliesmith',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '3a5f8738-c6ba-4aa1-8064-d51a5950488c',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-childrenspublishing',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => 'ed99622c-5637-479a-8f26-cbb102dfa750',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-broomtail',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '43286413-a8f7-4ee4-8d1d-de5eec08e41b',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-lildingus',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '66572ce0-f213-4592-b937-7f02f646b288',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-dreamer',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '19b508ac-f4be-4c59-a568-3ce5f391f4af',
    ],
    [
        'id' => '',
        'key' => 'brief-mood-service-click-rachelmovits',
        'entity_collection' => 'brand_wizard_references',
        'entity_id' => '43da62db-ce4b-42ad-833c-f16b0ac22f11',
    ],
    [
        'id' => '',
        'key' => 'portfolio-click-belyygorod',
        'entity_collection' => 'portfolio_projects',
        'entity_id' => '15fcd366-4ed3-4cfc-bc14-dfc9eccc34af',
    ],
    [
        'id' => '',
        'key' => 'portfolio-click-vilmers',
        'entity_collection' => 'portfolio_projects',
        'entity_id' => '0912ea90-564f-42f2-8c00-255b61fe16f6',
    ],
    [
        'id' => '',
        'key' => 'portfolio-click-sleco',
        'entity_collection' => 'portfolio_projects',
        'entity_id' => '0541f2d4-ba32-4b1a-92c0-c748a00bae45',
    ],
    [
        'id' => '',
        'key' => 'portfolio-click-boom',
        'entity_collection' => 'portfolio_projects',
        'entity_id' => '5fe51982-cdbe-4bcd-915d-196cdfe83eeb',
    ],
    [
        'id' => '',
        'key' => 'portfolio-click-lialab',
        'entity_collection' => 'portfolio_projects',
        'entity_id' => '7aa16a1f-df04-4573-8bbf-1c473bb21f6f',
    ],
    [
        'id' => '',
        'key' => 'portfolio-click-vegaburger',
        'entity_collection' => 'portfolio_projects',
        'entity_id' => '4810d921-0814-4d4b-912e-0cc340c86386',
    ],
    [
        'id' => '',
        'key' => 'brief-checkout-services-click-branding-and-style',
        'entity_collection' => 'brand_wizard_offers',
        'entity_id' => '179b3355-a00b-4e1e-b66f-8a307b593756',
    ],
    [
        'id' => '',
        'key' => 'brief-checkout-services-click-branding-and-box-design',
        'entity_collection' => 'brand_wizard_offers',
        'entity_id' => 'adcfc1db-c578-4d4a-9d0d-8f1ff4217699',
    ],
    [
        'id' => '',
        'key' => 'brief-checkout-services-click-startup',
        'entity_collection' => 'brand_wizard_offers',
        'entity_id' => 'e748f9a5-7683-4d5d-ae6a-344df08958e4',
    ],
    [
        'id' => '',
        'key' => 'brief-checkout-services-click-startup',
        'entity_collection' => 'brand_wizard_offers',
        'entity_id' => '4a69a458-c846-403c-9133-2c594cfeea0e',
    ],
];
